apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  namespace: demo
  labels:
    name: demo
    project: A
  annotations:
    created-by: team-A
spec:
  containers:
  - image: ssttehrani/7learn-k8s-demo-app:v1
    name: app
    ports:
    - containerPort: 8080
      protocol: TCP
