apiVersion: v1
kind: Pod
metadata:
  name: content-generator
  namespace: test
  labels:
    name: content-generator
spec:
  containers:
  - image: 7learn-k8s-content-gen:v3
    name: content-generator
    env:
    - name: INTERVAL
      value: "15"
    volumeMounts:
    - name: content
      mountPath: /var/contents
  volumes:
  - name: content
    emptyDir: {}
