kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # extraPortMappings:
  # - containerPort: 30100
  #   hostPort: 30101
- role: worker
  # extraPortMappings:
  # - containerPort: 30100
  #   hostPort: 30102
- role: worker
  # extraPortMappings:
  # - containerPort: 30100
  #   hostPort: 30103
