apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app
  namespace: test
  labels:
    name: app
    project: A
  annotations:
    created-by: team-A
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app
      project: A
    # matchExpressions:
    # - key: name
    #   operator: In
    #   values:
    #   - app
    # - key: project
    #   operator: Exists
  template:
    metadata:
      name: app
      labels:
        name: app
        project: A
    spec:
      containers:
      - image: ssttehrani/7learn-k8s-demo-app:v1
        name: app
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        livenessProbe:
          httpGet:
            port: http
            path: /
