apiVersion: v1
kind: ConfigMap
metadata:
  name: content-generator-config
  namespace: test
  labels:
    name: content-generator
data:
  interval: "10"
  custom.conf: |
    server {
      listen 80;
      listen 443 ssl;
      server_name test.local;

      ssl_certificate_key /etc/nginx/certs/tls.key;
      ssl_certificate /etc/nginx/certs/tls.cert;
      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }
