apiVersion: v1
kind: Pod
metadata:
  name: content-generator
  namespace: test
  labels:
    name: content-generator
spec:
  containers:
  - image: 7learn-k8s-content-gen:v3
    name: content-generator
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: content-generator-config
          key: interval
          optional: false
    volumeMounts:
    - name: content
      mountPath: /var/contents
  - image: nginx:alpine
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
      name: http
    volumeMounts:
    - name: ngx-cfg
      mountPath: /etc/nginx/conf.d/custom-config.conf
      subPath: custom.conf
    - name: ngx-certs
      mountPath: /etc/nginx/certs/
      readOnly: true
    - name: content
      mountPath: /usr/share/nginx/html
      readOnly: true
  volumes:
  - name: ngx-cfg
    configMap:
      name: content-generator-config
      items:
      - key: custom.conf
        path: custom.conf
  - name: ngx-certs
    secret:
      secretName: content-generator-nginx-secret
  - name: content
    emptyDir: {}
