apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-with-labels-2
  labels:
    name: demo
    project: A
    env: prod
spec:
  containers:
  - image: ssttehrani/7learn-k8s-demo-app:v1
    name: app
    ports:
    - containerPort: 8080
      protocol: TCP
