apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-with-nodeselector
  labels:
    name: demo
    project: test
    env: stg
spec:
  containers:
  - image: ssttehrani/7learn-k8s-demo-app:v1
    name: app
    ports:
    - containerPort: 8080
      protocol: TCP
  nodeSelector:
    disk: ssd
