apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: test
  labels:
    name: postgres
spec:
  containers:
  - image: postgres:15.1-alpine3.16
    name: postgres
    ports:
    - containerPort: 5432
      protocol: TCP
    volumeMounts:
    - name: data
      mountPath: /var/lib/postgresql/data
    env:
    - name: POSTGRES_PASSWORD
      value: password
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: postgres-pvc
