apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: test
  labels:
    name: postgres
spec:
  # Replace it with your node name
  # nodeName: test-worker
  containers:
  - image: postgres:15.1-alpine3.16
    name: postgres
    ports:
    - containerPort: 5432
      protocol: TCP
    volumeMounts:
    - name: data
      mountPath: /var/lib/postgresql/data
    env:
    - name: POSTGRES_PASSWORD
      value: password
    securityContext:
      runAsUser: 70
  volumes:
  - name: data
    nfs:
      # Replace it with your NFS server IP
      server: 192.168.1.106
      # Replace it with your NFS export path
      path: /data/postgres
