apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: test
  labels:
    name: app
  annotations:
    kubernetes.io/change-cause: |-
      Image tag set to v2
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app
  strategy:
    # rollingUpdate:
    #   maxSurge: 10%
    #   maxUnavailable: 10%
    type: RollingUpdate
  # minReadySeconds: 10
  template:
    metadata:
      name: app
      labels:
        name: app
    spec:
      containers:
      - image: ssttehrani/7learn-k8s-demo-app:v2
        name: app
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        # readinessProbe:
        #   httpGet:
        #     port: http
        #     path: /
        #   periodSeconds: 1
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 1
