apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-2
spec:
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    # Replace it with your NFS server IP
    server: 192.168.1.104
    # Replace it with your NFS export path
    path: /data/demo-app/2
  storageClassName: ""
