apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
  labels:
    name: node-exporter
    project: prometheus
spec:
  selector:
    matchLabels:
      name: node-exporter
  template:
    metadata:
      name: node-exporter
      labels:
        name: node-exporter
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      #nodeSelector:
        #gpu: enabled
      containers:
      - image: prom/node-exporter:latest
        name: prometheus-node-exporter
        ports:
        - containerPort: 9100 
          protocol: TCP
          name: http
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
