apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: test
spec:
  selector:
    name: app
  ports:
  - port: 80
    targetPort: 8080
    # targetPort: http
    # name: http
  # - port: 443
  #   targetPort: 8443
  #   name: https
  # sessionAffinity: ClientIP
